### PR TITLE
Media window popup

### PR DESCRIPTION
**Pull request by k0kubun**
Temporarily saved branch of https://github.com/k0kubun/Nocturn/pull/43.

### CODE REVIEW

**Comment by CandyFace** [comment]
Alright we're getting there. You mentioned you've discovered another problem right? Would that by any chance be that if you open a second image while the first is still open, then both windows will be resized? if not, that's another bug I discovered earlier, however since BrowserWindow doesn't seem to keep reference on which window to close, i'm not sure how we can fix that.

**Comment by k0kubun** [comment]
In addition, tweets I commented in https://github.com/k0kubun/Nocturn/pull/47#issuecomment-255596368 can't be displayed.

**Comment by CandyFace** [comment]
Ahh yes I noticed that too... it seems that Twitter very recently switched to another video format -.-' m3u8 which is hls, though twitters api doesn't seem to mention how to get this anymore yet, but it's supposedly going to be used instead of mp4 soon.

**Comment by CandyFace** [comment]
Okay I've managed to get the m3u8 into our video container but it still won't play... We may have to import a hls library for it to work.

**Pull request merged**
