### PR TITLE
Fixed window sizing

### PR DESCRIPTION
**Pull request by CandyFace**
Last changes to the window. Doesn't move after being opened now, titleBarStyle only hidden on OSX, height is also only +20 on osx.

### CODE REVIEW

**Comment by CandyFace** [comment]
Damn it.. didn't notice the conflict.. -.- will fix!

**Comment by k0kubun** [comment]
Oh, sorry for a sudden merge. Could you rebase this branch against master? 

In addition, a commit like "Merge remote-tracking branch" shouldn't be added.

**Comment by CandyFace** [comment]
There.. jeeus man I hate conflicts.. even if it's just rebasing I always mange to fuck up it commit wise... D: sorry about the remote tracking too :/

**Comment by k0kubun** [comment]
Please study git.

1. [fixed-window-sizing] git checkout master
2. [master] git pull origin master
3. [master] git checkout fixed-window-sizing
4. [fixed-window-sizing] git rebase master
5. [fixed-window-sizing|rebase] git add *conflicted files* (after fixing conflict)
6. [fixed-window-sizing|rebase] git rebase --continue
7. [fixed-window-sizing] git push --force *your-remote* fixed-window-sizing

<hr>

Now this branch is broken. Before avobe steps, you should do:

1. git checkout master
2. git branch -D fixed-window-sizing
3. git checkout -b fixed-window-sizing

**Comment by CandyFace** [comment]
Sorry.. I'll remove this branch and do above.. I do know git but I still seem to fuck up commits.

**Pull request closed without merging**
