### PR TITLE
Support multiple attached photos

### LINKED ISSUE #23: Only shows one attached images
Twitter supports up to 4, but Nocturn only shows one - first.

### PR DESCRIPTION
**Pull request by IzumiSy**
This PR will close #23

### CODE REVIEW

**Comment by IzumiSy** [comment]
Sorry this still looks to have some bugs.

**Comment by IzumiSy** [comment]
Fixed

**Comment by k0kubun** [comment]
Nice feature :+1: 
I'll tweak some styles to prevent overlaps for some cases.

**Comment by IzumiSy** [comment]
Thanks!

**Pull request merged**
