### PR TITLE
Drop fixes

### PR DESCRIPTION
**Pull request by k0kubun**
Closes https://github.com/k0kubun/Nocturn/issues/46

### CODE REVIEW

**Comment by CandyFace** [comment]
I think it can be fixed actually, it seems that this for some propertirs are by default writable: false, but if we can make this.videoWidth and this.videoHeight writable, then it should work.

I'm looking into it atm. but it requires   Object.defineProperties()

**Comment by k0kubun** [comment]
Removed a whole changes from master for now. Working version of https://github.com/k0kubun/Nocturn/pull/48 will be merged but I have less time to do it by myself for now.

**Comment by CandyFace** [comment]
Aha! I figured it, else if we change from
```
else {
    this.videoWidth = mediaWidth;
    this.videoHeight = mediaHeight;
  }
```
to:
```
else {
    media.videoWidth = mediaWidth;
    media.videoHeight = mediaHeight;
  }
```

Then it works. What was the other problem you found?

**Comment by k0kubun** [comment]
Applied in https://github.com/k0kubun/Nocturn/pull/48/commits/71624bf20bfc2c1fdda33a06725097535d9c8ea6 .

At least this branch didn't work for https://twitter.com/Catfish_nama/status/790166810511355904/video/1 and https://twitter.com/watson20150512/status/790134132474990592/video/1.

**Pull request merged**
